# src/latest_ai_development/config/tasks.yaml

research_task:
  description: >
    Search for relevant information from {university} about {topic}.
    Provide a list of professors or labs along with their URLs
    that are actively working on this topic.
  expected_output: >
    A valid JSON object matching the specified Pydantic model, with:
    - A list of professors (name, research_interests, contact_email, url)
    - A list of labs (name, focus, url)
  agent: researcher
  output_file: outputs/research_info.json
  create_directory: true

# chat_task:
#   name: "User Satisfaction Chat"
#   description: >
#     Ask the user if they are satisfied with the list of professors and labs.
#     If not, prompt them to provide more detailed information about their preferences.
#     If yes, provide the contact information of the selected professor.
#   expected_output: >
#     - User satisfaction with the research results
#     - Additional details if needed
#     - Final selection of a professor or lab
#     - Confirmation of the choice
#     - If Satisfied: Provide contact information of the selected professor
#     - If Not Satisfied: Prompt for more details until satisfaction
#   human_input: false  # This task does not require human input
#   agent: chat_agent
