# tasks.yaml

research_task:
  task_id: research_task
  description: >
    Search for relevant information from {university} about {topic}.
    Provide a list of professors or labs along with their URLs
    that are actively working on this topic.
  expected_output: >
    A valid JSON object matching the specified Pydantic model, with:
    - A list of professors (name, research_interests, contact_email, url)
    - A list of labs (name, focus, url)
  agent: researcher
  output_file: outputs/research_info.json
  create_directory: true

professor_research_task:
  task_id: professor_research_task
  description: >
    Given a professor or lab name and URL, research their research interests, projects, 
    publications, and courses. 
  expected_output: >
    A valid JSON object with keys 'publications', 'projects', 'courses' 
    (each a list of objects or strings).
    Output must be valid JSON. For publications, produce a list of objects with title and summary. 
    For projects, produce a list of objects with name and description. For courses, produce a list of strings. No extra text outside of JSON.
  agent: deeper_researcher
  output_file: outputs/specific_info.json
  create_directory: true

cover_letter_task:
  task_id: cover_letter_task
  description: >
    Given the chosen professor's details, plus the student's resume text {resume}, 
    write a succinct, professional email subject, email body, 
    and a separate cover letter. 
  expected_output: >
    A valid JSON object matching the specified Pydantic model, with:
    -"email_subject": "...",
    -"email_body": "...",
    -"cover_letter": "..."
  agent: cover_letter_agent
  output_file: outputs/cover_letter.json
  create_directory: true
