research_task:
  description: >
    Search for relevant information from {university} about {topic}.
    Provide a list of professors or labs along with their URLs
    that are actively working on this topic.
  expected_output: >
    A valid JSON object matching the specified Pydantic model, with:
    - A list of professors (name, research_interests, contact_email, url)
    - A list of labs (name, focus, url)
  agent: researcher
  output_file: outputs/research_info.json
  create_directory: true

deeper_research_task:
  description: >
    Perform detailed research on {prof_name}. Provide background, key publications,
    achievements, or relevant notes about them.
  expected_output: >
    A valid JSON object matching the ProfessorDetail model:
      -"name": "...",
      -"biography": "...",
      -"notable_publications": [...],
      -"research_focus": "..."
  agent: deeper_researcher
  output_file: outputs/professor_detail.json
  create_directory: true
